import "./Buttons.css"
import { Button } from "../../atoms/Button"
import BackspaceSymbol from "../../../assets/backspace_symbol.png"

export const Buttons = ({
  handleButtonClicked,
  isCalculateDisabled,
  isDeleteDisabled
}) => (
  <div id="buttons">
    <Button
      className="specialOperation"
      content="&#8730;"
      handleButtonClicked={handleButtonClicked}
    />
    <Button
      className="specialOperation"
      content="&sup2;"
      handleButtonClicked={handleButtonClicked}
    />
    <Button
      className="operator"
      content="&#94;"
      handleButtonClicked={handleButtonClicked}
    />
    <Button
      className="operator"
      content="/"
      handleButtonClicked={handleButtonClicked}
    />
    <Button
      className="number"
      content="7"
      handleButtonClicked={handleButtonClicked}
    />
    <Button
      className="number"
      content="8"
      handleButtonClicked={handleButtonClicked}
    />
    <Button
      className="number"
      content="9"
      handleButtonClicked={handleButtonClicked}
    />
    <Button
      className="operator"
      content="*"
      handleButtonClicked={handleButtonClicked}
    />
    <Button
      className="number"
      content="4"
      handleButtonClicked={handleButtonClicked}
    />
    <Button
      className="number"
      content="5"
      handleButtonClicked={handleButtonClicked}
    />
    <Button
      className="number"
      content="6"
      handleButtonClicked={handleButtonClicked}
    />
    <Button
      className="operator"
      content="-"
      handleButtonClicked={handleButtonClicked}
    />
    <Button
      className="number"
      content="1"
      handleButtonClicked={handleButtonClicked}
    />
    <Button
      className="number"
      content="2"
      handleButtonClicked={handleButtonClicked}
    />
    <Button
      className="number"
      content="3"
      handleButtonClicked={handleButtonClicked}
    />
    <Button
      className="operator"
      content="+"
      handleButtonClicked={handleButtonClicked}
    />
    <Button
      content="C"
      handleButtonClicked={handleButtonClicked}
      id="clear"
    />
    <Button
      className="number"
      content="0"
      handleButtonClicked={handleButtonClicked}
    />
    <Button
      disabled={isDeleteDisabled}
      handleButtonClicked={handleButtonClicked}
      id="delete"
    >
      <img src={BackspaceSymbol} alt="Delete button" />
    </Button>
    <Button
      content="="
      disabled={isCalculateDisabled}
      handleButtonClicked={handleButtonClicked}
      id="calculate"
    />
  </div>
);
